services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CrossSelling\Core\Content\CrossSellingGroup\CrossSellingGroupDefinition:
    tags:
      - { name: 'shopware.entity.definition' }

  CrossSelling\Subscriber\ProductPageSubscriber:
    arguments:
      $categoryRepo: '@category.repository'
      $crossSellingGroupRepo: '@cross_selling_product_group.repository'
      $productStreamRepo: '@product_stream.repository'
      $productStreamBuilder: '@Shopware\Core\Content\ProductStream\Service\ProductStreamBuilder'
      $productListingLoader: '@Shopware\Core\Content\Product\SalesChannel\Listing\ProductListingLoader'
      $systemConfigService: '@Shopware\Core\System\SystemConfig\SystemConfigService'
    tags:
      - { name: kernel.event_subscriber }